version: '3.1'

services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_USER: thor
      MYSQL_PASSWORD: patrik
      MYSQL_DATABASE: beti
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/data
    networks:
      - app-network
  
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nest-app:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: thor
      MYSQL_PASSWORD: patrik
      MYSQL_DB: beti
      JWT_SECRET: altron
      JWT_EXPIRATION_TIME: 7200
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    networks:
      - app-network

volumes:
  redis-data:
  mysql-data:

networks:
  app-network:
